---
version: "2.1"
services:
  ubooquity:
    image: lscr.io/linuxserver/calibre:arch
    container_name: calibre
    environment:
      - PUID=2077
      - PGID=2077
      - TZ=America/New_York
    volumes:
      - /srv/docker/calibre/config:/config
      - /mnt/calibre/ebooks:/data/ebooks/
    ports:
      - 8084:8080
      - 8085:8081
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1         

networks:
  default:
    external:
      name: arr_network
