---
version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=2060
      - PGID=2060
      - TZ=America/New_York
    volumes:
      - /srv/docker/lidarr/config/:/config
      - /mnt/lidarr/music:/data/music #optional
      - /mnt/lidarr/downloads:/data/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1         

networks:
  default:
    external:
      name: arr_network
