---
#setup raspberry pi

- hosts: pis
  become: yes
  become_method: sudo
  roles:
    - pi

- hosts: pi-nas
  become: yes
  become_method: sudo
  roles:
    - nas

- hosts: pi-plex
  become: yes
  become_method: sudo
  roles:
    - plex
   
#- hosts: pi-dvr
#  become: yes
#  become_method: sudo
#  roles:
#    - dvr
