---
- hosts: linux_servers #MJS - should be linux
  become: yes
  become_method: sudo
  roles:
    - linux

- hosts: pi_servers
  become: yes
  become_method: sudo
  roles:
    - pi

- hosts: raspbian_os_servers
  become: yes
  become_method: sudo
  roles:
    - raspbian

  hosts: docker_servers
  become: yes
  become_method: sudo
  roles:
    - docker

- hosts: arr_servers
  become: yes
  become_method: sudo
  roles:
    - arr

# - hosts: plexUbuntu_servers
#  become: yes
#  become_method: sudo
#  roles:
#    - plex-ubuntu
#    - plex

#- hosts: pi_hole_servers
#  become: yes
# become_method: sudo
#  roles:
#    - pi-hole
