---
#- hosts: all #MJS - should be linux
#  become: yes
#  become_method: sudo
#  roles:
#    - global

#- hosts: pi_servers
#  become: yes
#  become_method: sudo
#  roles:
#    - pi

#- hosts: raspbian_os_servers
#  become: yes
#  become_method: sudo
#  roles:
#    - raspbian

#  hosts: docker_servers
#  become: yes
#  become_method: sudo
#  roles:
#    - docker

- hosts: dvr_servers
  become: yes
  become_method: sudo
  roles:
    - dvr

- hosts: plexUbuntu_servers
  become: yes
  become_method: sudo
  roles:
    - plex-ubuntu
    - plex

- hosts: pi_hole_servers
  become: yes
  become_method: sudo
  roles:
    - pi-hole
