---
- hosts: raspbian
  become: yes
  become_method: sudo
  roles:
    - global
    - pi
    - raspbian

- hosts: pi-nas
  become: yes
  become_method: sudo
  roles:
    - global
    - nas
 
- hosts: pi-dvr
  become: yes
  become_method: sudo
  roles:
    - global
    - dvr

- hosts: plexUbuntu
  become: yes
  become_method: sudo
  roles:
    - global
    - plex-ubuntu

- hosts: pi-hole
  become: yes
  become_method: sudo
  roles:
    - global
    - pi-hole
