---
- hosts: raspbian_os_servers
  become: yes
  become_method: sudo
  roles:
    - global
    - pi
    - raspbian

#- hosts: pinas
#  become: yes
#  become_method: sudo
#  roles:
#    - global
#    - nas
 
- hosts: dvr_servers
  become: yes
  become_method: sudo
  roles:
    - global
    - dvr

- hosts: plexUbuntu_servers
  become: yes
  become_method: sudo
  roles:
    - global
    - plex-ubuntu
    - plex

- hosts: pi_hole_servers
  become: yes
  become_method: sudo
  roles:
    - global
    - pi-hole
