---
- name: set host name
  hostname:  
   name: "{{inventory_hostname}}"

- name: Include vault
  include_vars:
    file: vault.yml

- name: change default passwords
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
  with_items: "{{ system_users }}"
  loop_control:
    label: "{{ item.username }}"
