---
- name: set host name
  hostname:  
   name: "{{inventory_hostname}}"

- name: Include vault
  include_vars:
    file: vault.yml

- name: change default passwords
  user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512', password_salt ) }}"
    update_password: always
  with_items: "{{ system_users }}"
  loop_control:
    label: "{{ item.username }}"
   
- name: add dns server entries
  lineinfile:
    path: /etc/dhcpcd.conf
    regexp: "^static domain_name_servers="
    line: "static domain_name_servers={{ nameserver_ip }}"
    state: present
  register: dnsupdate
  
- name: restart dns if changed
  service:
    name: dhcpcd
    state: restarted
  when: dnsupdate.changed

