---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=2020
      - PGID=2020
      - TZ=America/New_York
    volumes:
      - /srv/docker/bazarr/config/:/config
      - /mnt/bazarr/tv:/data/tv #optional
      - /mnt/bazarr/movies:/data/movies/ #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1         

networks:
  default:
    external:
      name: arr_network
