---
version: "2.1"
services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=2080
      - PGID=2080
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /srv/docker/lazyLibrarian/config/:/config
      - /mnt/lazyLibrarian/library:/mnt/lazyLibrarian/library #optional
      - /mnt/lazyLibrarian/downloads:/srv/data/nzb/downloads #optional
    ports:
      - 5299:5299
    restart: unless-stopped
