---
- name: include vault
  include_vars:
    file: vault.yml

- name: create users
  user:
    name: "{{ item.username }}"
    password: "{{ (global_users_passwords | selectattr('username', 'equalto', item.username) | first).password | password_hash('sha512', password_salt) }}"
    update_password: always
    state: present
  with_items:
    - "{{ global_users }}"

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Add user "mastrick" to sudo
  lineinfile:
    path: /etc/sudoers.d/mastrick
    line: 'mastrick ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: '/usr/sbin/visudo -cf %s'
