---
- name: include vault
  include_vars:
    file: vault.yml

- name: install docker
  apt:
    pkg:
      - docker
      - docker-compose
  register: aptupdate

- name: reboot on apt update
  reboot:
    test_command: whoami
  when: aptupdate.changed
