---
- name: include vault
  include_vars:
    file: vault.yml

#- name: setup docker
#  include: docker.yml

#- name: Create the arr network
#  docker_network:
#    name: arr_network

- name: increase swap space
  include: swapspace.yml

- name: install necessary packages
  apt:
    pkg:
     - gpg
     - samba
     - samba-common-bin
     - cifs-utils
     - smbclient
    state: latest
    
#- name: setup nzbget
#  include: nzbget.yml    
  
- name: setup *arr
  include: arr.yml
  vars:
    settings: "{{ settings_object }}"
  loop_control:
    loop_var: settings_object
  with_items:
#    - "{{ prowlarr_settings }}"
    - "{{ radarr_settings }}"
    - "{{ lidarr_settings }}"    
    - "{{ sonarr_tv_settings }}"
    - "{{ sonarr_anime_settings }}"
    - "{{ sonarr_ended_settings }}"
    - "{{ readarr_settings }}"        
#    - "{{ sonarr_bazarr_settings }}"

#- name: setup prowlarr
#  include: prowlarr.yml

#- name: setup bazarr
#  include: bazarr.yml

###- name: setup qbt
###  include: torrent.yml

###- name: install vpn
###  include: vpn.yml

###- name: setup firewall
###  include: firewall.yml

