---
- name: include vault
  include_vars:
    file: vault.yml

- name: create group
  group:
    name: dvr
    state: present

- name: salt password
  set_fact:
    salted_password: "{{ dvr_password | password_hash('sha512', password_salt) }}"
    run_once: true

- name: create user
  user:
    name: "{{ dvr_username }}"
    password: "{{ salted_password }}"
    update_password: always
    group: "{{ dvr_username }}"

- name: setup docker
  include: docker.yml

- name: Create the arr network
  docker_network:
    name: arr_network

- name: setup nzbget
  include: nzbget.yml

#- name: install vpn
#  include: vpn.yml

#- name: setup firewall
#  include: firewall.yml


#- name: setup sonarr
#  include: sonarr.yml

#- name: setup prowlarr
#  include: prowlarr.yml

#- name: setup bazarr
#  include: bazarr.yml

#- name: setup radarr
#  include: radarr.yml

#- name: setup lidarr
#  include: lidarr.yml

#- name: setup readarr
#  include: readarr.yml

#- name: setup lazyLibrarian
#  include: lazyLibrarian.yml

#- name: setup qbt
#  include: torrent.yml
