---
- name: include vault
  include_vars:
    file: vault.yml

- name: create nzbget group
  group:
    name: "{{ nzbget_username }}"
    gid: "{{ nzbget_gid }}"
    state: present

- name: create nzbget user
  user: 
    name: "{{ nzbget_username }}"
    uid: "{{ nzbget_uid }}"
    state: present
    group: "{{ nzbget_username }}"

- name: add nzbget to docker group
  user:
    name: "{{ nzbget_username }}"
    groups: docker
    append: yes

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: "{{ nzbget_uid }}"
   group: "{{ nzbget_gid }}"
  with_items:
   - '/mnt/nzbget'

- name: add mounts to fstab
  lineinfile:
   path: /etc/fstab
   line: "{{ item }}"
   create: yes
  with_items:
   - "//{{ media_nas_name }}/nzb /mnt/nzbget cifs username={{ nzbget_smb_creds.username }},password={{ nzbget_smb_creds.password }},iocharset=utf8,uid={{ nzbget_uid }},gid={{ nzbget_gid }},file_mode=0755,dir_mode=0755,vers=3.1.1"

- name: mount all
  command: mount -a
  args:
    warn: no

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: "{{ nzbget_uid }}"
   group: "{{ nzbget_gid }}"
  with_items:
   - '/mnt/nzbget/downloads'
   - '/mnt/nzbget/config'   

- name: get docker image
  docker_image:
    name: "linuxserver/nzbget"
    source: pull

- name: deploy config script
  copy:
    src: mnt/nzbget/config/nzbget.conf
    dest: /mnt/nzbget/config/nzbget.conf
    owner: "{{ nzbget_uid }}"
    group: "{{ nzbget_gid }}" 
    remote_src: no    

- name: create directories for nzbget docker image
  file:
    path: "{{ item }}"
    state: directory
    owner: nzbget
    group: nzbget
  with_items:
    - /srv/docker/nzbget

- name: copy docker-compose file
  copy: 
    src: srv/docker/nzbget/docker-compose.yml
    dest: /srv/docker/nzbget/docker-compose.yml
    owner: "{{ nzbget_uid }}"
    group: "{{ nzbget_gid }}"
    remote_src: no

- name: deploy init script
  copy:
    src: etc/systemd/system/docker.nzbget.service
    dest: /etc/systemd/system/docker.nzbget.service

- name: enable docker nzbget service
  service:
    name: docker.nzbget
    state: restarted
    enabled: yes
    daemon_reload: yes    
