---
- name: create sonarr group
  group:
    name: sonarr
    state: present

- name: create sonarr user
  user: 
    name: sonarr
    state: present
    group: sonarr

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: sonarr
   group: sonarr
  with_items:
   - '/mnt/sonarr'
   - '/mnt/sonarr/tv'

- name: install necessary packages
  apt:
    pkg:
     - gpg
     - samba
     - samba-common-bin
     - cifs-utils
     - smbclient
    state: latest
    update_cache: true

- name: add mounts to fstab
  lineinfile:
   path: /etc/fstab
   line: "{{ item }}"
   create: yes
  with_items:
   - "//nas02.private/Videos/tv    /mnt/sonarr/tv cifs username={{ sonarr_creds.username }},password={{ sonarr_creds.password }},iocharset=utf8,uid=sonarr,gid=sonarr,file_mode=0755,dir_mode=0755,vers=3.1.1"

- name: mount all
  command: mount -a
  args:
    warn: no

- name: add mono key
  apt_key:
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present

- name: add mono repo
  apt_repository:
    repo: deb https://download.mono-project.com/repo/debian stable-raspbianbuster main
    state: present
    filename: mono-official-stable

- name: install mono
  apt:
   pkg:
    - mono-devel
   state: latest
   update_cache: true

- name: add sonarr key
  apt_key:
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8
    keyserver: keyserver.ubuntu.com
    state: present

- name: add sonarr repo
  apt_repository:
    repo: deb https://apt.sonarr.tv/debian buster main
    state: present
    filename: sonarr

- name: install sonarr
  apt:
    pkg:
     - sonarr
    state: latest
    update_cache: true
