---
- name: include vault
  include_vars:
    file: vault.yml

- name: install docker
  apt:
    pkg:
      - docker
      - docker-compose
  register: aptupdate

- name: reboot on apt update
  reboot:
    test_command: whoami
  when: aptupdate.changed

- name: create sonarr group
  group:
    name: "{{ sonarr_creds.username }}"
    gid: 2000
    state: present

- name: create sonarr user
  user: 
    name: "{{ sonarr_creds.username }}"
    uid: 2000
    state: present
    group: "{{ sonarr_creds.username }}"

- name: add pihole to docker group
  user:
    name: "{{ sonarr_creds.username }}"
    groups: docker
    append: yes

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: "{{ sonarr_creds.username }}"
   group: "{{ sonarr_creds.username }}"
  with_items:
   - '/mnt/sonarr'
   - '/mnt/sonarr/tv'
   - '/mnt/sonarr/downloads'

- name: install necessary packages
  apt:
    pkg:
     - gpg
     - samba
     - samba-common-bin
     - cifs-utils
     - smbclient
    state: latest
    update_cache: true

- name: add mounts to fstab
  lineinfile:
   path: /etc/fstab
   line: "{{ item }}"
   create: yes
  with_items:
   - "//nas02/Videos/tv /mnt/sonarr/tv cifs x-systemd.automount,noauto,_netdev,username={{ sonarr_creds.username }},password={{ sonarr_creds.password }},iocharset=utf8,uid=sonarr,gid=sonarr,file_mode=0755,dir_mode=0755,vers=3.1.1"
   - "//nas02/temp_nzb/downloads/ /mnt/sonarr/downloads cifs x-systemd.automount,noauto,_netdev,username={{sonarr_creds.username }},password={{ sonarr_creds.password }},iocharset=utf8,uid=sonarr,gid=sonarr,file_mode=0755,dir_mode=0755,vers=3.1.1"

- name: mount all
  command: mount -a
  args:
    warn: no

- name: get docker image
  docker_image:
    name: linuxserver/sonarr
    source: pull

- name: create directories for sonarr docker image
  file:
    path: "{{ item }}"
    state: directory
    owner: sonarr
    group: sonarr
  with_items:
    - /srv/docker/sonarr
    - /srv/docker/sonarr/tv
    - /srv/docker/sonarr/anime
    - /srv/docker/sonarr/ended

- name: copy docker-compose file
  copy: 
    src: srv/docker/sonarr/tv/docker-compose.yml
    dest: /srv/docker/sonarr/tv/docker-compose.yml
    owner: "{{ sonarr_creds.username }}"
    group: "{{ sonarr_creds.username }}"
    remote_src: no

- name: copy docker-compose file
  copy:
    src: srv/docker/sonarr/anime/docker-compose.yml
    dest: /srv/docker/sonarr/anime/docker-compose.yml
    owner: "{{ sonarr_creds.username }}"
    group: "{{ sonarr_creds.username }}"
    remote_src: no

- name: copy docker-compose file
  copy:
    src: srv/docker/sonarr/ended/docker-compose.yml
    dest: /srv/docker/sonarr/ended/docker-compose.yml
    owner: "{{ sonarr_creds.username }}"
    group: "{{ sonarr_creds.username }}"
    remote_src: no

- name: deploy init script
  copy:
    src: etc/systemd/system/docker.sonarr.tv.service
    dest: /etc/systemd/system/docker.sonarr.tv.service

- name: deploy init script
  copy:
    src: etc/systemd/system/docker.sonarr.anime.service
    dest: /etc/systemd/system/docker.sonarr.anime.service

- name: deploy init script
  copy:
    src: etc/systemd/system/docker.sonarr.ended.service
    dest: /etc/systemd/system/docker.sonarr.ended.service

- name: enable docker sonarr service
  service:
    name: docker.sonarr.tv
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable docker sonarr service
  service:
    name: docker.sonarr.anime
    state: started
    enabled: yes
    daemon_reload: yes

- name: enable docker sonarr service
  service:
    name: docker.sonarr.ended
    state: started
    enabled: yes
    daemon_reload: yes


