---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=3020
      - PGID=3020
      - TZ=America/New_York
    volumes:
      - /srv/docker/heimdall/config/:/config
    ports:
      - 81:80
      - 444:443
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1    

networks:
  default:  
    external:  
      name: arr_network

