---
- name: include vault
  include_vars:
    file: vault.yml

- name: Create the arr network
  docker_network:
    name: arr_network

- name: increase swap space
  include: swapspace.yml

- name: install necessary packages
  apt:
    pkg:
     - samba
     - samba-common-bin
     - cifs-utils
     - smbclient
    state: latest
    
 - name: setup nzbget
   include: nzbget.yml    

- name: nginx directories
  file:
   path: "{{ item }}"
   state: directory
   owner: "3010"
   group: "3010"
  with_items:
   - '/srv/docker/nginx'
   - '/srv/docker/nginx/config'
   - '/srv/docker/nginx/certbot/conf'
   - '/srv/docker/nginx/certbot/www'
  
- name: nginx prep
  copy:
    src: srv/docker/nginx/config/nginx.conf
    dest: /srv/docker/nginx/config/nginx.conf
    owner: "3010"
    group: "3010"
    remote_src: no    
  
- name: setup docker containers
  include: containers.yml
  vars:
    settings: "{{ settings_object }}"
  loop_control:
    loop_var: settings_object
  with_items:
    - "{{ nginx_settings }}"
    - "{{ heimdall_settings }}"    
    - "{{ prowlarr_settings }}"
    - "{{ radarr_settings }}"
    - "{{ lidarr_settings }}"    
    - "{{ sonarr_tv_settings }}"
    - "{{ sonarr_anime_settings }}"
    - "{{ sonarr_ended_settings }}"
    - "{{ mylar_settings }}"      
    - "{{ overseerr_settings }}"    
    - "{{ ubooquity_settings }}"
    - "{{ qbittorrent_settings }}"

#    - "{{ bazarr_settings }}"    
#    - "{{ readarr_ebook_settings }}"        
#    - "{{ readarr_audio_settings }}"        
#    - "{{ calibre_settings }}"    
#    - "{{ calibreweb_settings }}"

