---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr_anime
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
    volumes:
      - /srv/docker/sonarr/anime/config/:/config
      - /mnt/sonarr/tv:/data/tv #optional
      - /mnt/sonarr/downloads:/data/downloads #optional
    ports:
      - 8988:8989
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1        

networks:
  default:
    external:
      name: arr_network
