---
version: "2.1"
services:
  ubooquity:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibreweb
    environment:
      - PUID=2077
      - PGID=2077
      - TZ=America/New_York
    volumes:
      - /srv/docker/calibreweb/config:/config
      - /mnt/calibre/ebooks:/books
    ports:
      - 8083:8083
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1         

networks:
  default:
    external:
      name: arr_network
