---
- name: install packages
  apt:
    pkg:
      - aptitude
    state: latest
    update_cache: true

- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: Remove packages from cache
  apt:
    autoclean: yes

- name: Remove unused dependencies
  apt:
    autoremove: yes

- name: remove other localhost definitions
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.0\.1[ \t\s]*((?!localhost\t{{inventory_hostname}}).)*$'
   state: absent

- name: update hosts file with hostname
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.0\.1'
   line: "127.0.0.1\tlocalhost\t{{inventory_hostname}}"
   insertbefore: BOF
   owner: root
   group: root
   mode: '0644'

- name: update hosts file with hostname
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.1\.1'
   line: "127.0.1.1\tlocalhost\t{{inventory_hostname}}"
   insertbefore: BOF
   owner: root
   group: root
   mode: '0644'

- name: create user
  user:
    name: mastrick
    password: $6$228438166$VVSp4qoPQObdWBg5yzcCzHL02sxHmgKXPUFHQS/3N6kiNk2Tc5wKpTUq12mZvhnGFqgV58josHlphyZolYyYh/
    update_password: always
