---
- name: add key for rpi monitor
  apt_key:
    id: 2C0D3C0F
    keyserver: keyserver.ubuntu.com
    state: present

- name: add rpi monitor repo
  apt_repository:
    repo: deb http://giteduberger.fr rpimonitor/
    state: present
    filename: rpimonitor

- name: install packages
  apt:
    pkg:
      - aptitude
      - samba
      - samba-common-bin
      - cifs-utils
      - smbclient
      - rpimonitor
      - unzip
    state: latest
    update_cache: true

- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300

- name: Remove packages from cache
  apt:
    autoclean: yes

- name: Remove unused dependencies
  apt:
    autoremove: yes

- name: remove other localhost definitions
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.0\.1[ \t\s]*((?!localhost {{inventory_hostname}}).)*$'
   state: absent

- name: remove other localhost definitions
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.1\.1[ \t\s]*((?!localhost {{inventory_hostname}}).)*$'
   state: absent

- name: update hosts file with hostname
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.0\.1'
   line: "127.0.0.1 localhost {{inventory_hostname}}"
   insertbefore: BOF
   owner: root
   group: root
   mode: '0644'

- name: update hosts file with hostname
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.1\.1'
   line: "127.0.1.1 localhost {{inventory_hostname}}"
   insertbefore: BOF
   owner: root
   group: root
   mode: '0644'
