---

- name: install packages
  apt:
    pkg:
    - samba
    - samba-common-bin
    state: present

- name: Include samba vault
  include_vars:
    file: vault.yml

- name: Configure Samba users.
  shell: >
    (pdbedit --user={{ item.username }} 2>&1 > /dev/null)
    || (echo '{{ item.password }}'; echo '{{ item.password }}')
    | smbpasswd -s -a {{ item.username }}
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  with_items: "{{ samba_users }}"
  loop_control:
    label: "{{ item.username }}"
  notify:
   - Restart Samba service
   - Restart NetBIOS name service

- name: deploy samba conf
  copy:
   src: etc/samba/smb.conf
   dest: /etc/samba/smb.conf
   owner: root
   group: root
  notify:
   - Restart Samba service
