---
# main nas pi tasks
- name: install pre-reqs
  include: install-pre-reqs.yml

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: pi
   group: pi
  with_items:
   - '/mnt/external01'
   - '/mnt/external01/data/download'
   - '/mnt/external02'

- name: create symbolic link for downloads
  file:
   src: /mnt/external01/data/download
   dest: /srv/data/download
   owner: pi
   group: pi
   state: link

- name: create symbolic link for stream
  file:
   src: /mnt/external02/data/stream
   dest: /srv/data/stream
   owner: pi
   group: pi
   state: link

- name: add mounts to fstab
  lineinfile:
   path: /etc/fstab
   line: "{{ item }}"
   create: yes
  with_items:
   - '/dev/disk/by-uuid/d0abd076-4973-46fe-9ffc-ab89bdd92102     /mnt/external01     ext4     defaults 0 0'
   - '/dev/disk/by-uuid/44cddade-da5e-4da3-98ea-6d3d6d7c72bf     /mnt/external02     ext4     defaults 0 0'   

- name: create user
  user:
    name: nzb
    password: $6$228438166$tpfWAOPpKR5GLmXzJimwi5zQ3dg0EVz5dgeMUVjsEVWT4CzRYZN26Oxu4UOXcwk06GzqifYRdkZohuixNCbjc.
    update_password: on_create
    
- name: Configure Samba
  include: config-samba.yml

- name: Configure TGT
  include: config-tgt.yml

- name: Configure NFS
  include: config-nfs.yml
