---
# main nas pi tasks
- name: install pre-reqs
  include: install-pre-reqs.yml

- name: set host name
  hostname:  
   name: pi-nas01

- name: change default pi password
  user: name=pi password=$6$228438166$WZeDX53ZvFdq989jimlLwXp.twAwI10aODeEdcGiePf/j8CHk46llsQlGdfvviz1x701vpP3OWAJduiNHShk80

- name: remove other localhost definitions
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.0\.1[ \t\s]*((?!localhost\tpi-nas01).)*$'
   state: absent

- name: update hosts file with hostname
  lineinfile:
   path: /etc/hosts
   regexp: '^127\.0\.0\.1'
   line: "127.0.0.1\tlocalhost\tpi-nas01"
   insertbefore: BOF
   owner: root
   group: root
   mode: '0644'

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: pi
   group: pi
  with_items:
   - '/mnt/external01'
   - '/mnt/external02'
#   - '/srv/stream/'

- name: create symbolic link for stream
  file:
   src: /mnt/external02/data/stream
   dest: /srv/data/stream
   owner: pi
   group: pi
   state: link

- name: add mounts to fstab
  lineinfile:
   path: /etc/fstab
   line: "{{ item }}"
   create: yes
  with_items:
   - '/dev/disk/by-uuid/d0abd076-4973-46fe-9ffc-ab89bdd92102     /mnt/external01     ext4     defaults 0 0'
   - '/dev/disk/by-uuid/44cddade-da5e-4da3-98ea-6d3d6d7c72bf     /mnt/external02     ext4     defaults 0 0'   

- name: create user
  user:
    name: mastrick
    password: $6$228438166$VVSp4qoPQObdWBg5yzcCzHL02sxHmgKXPUFHQS/3N6kiNk2Tc5wKpTUq12mZvhnGFqgV58josHlphyZolYyYh/
    update_password: on_create
    
- name: Configure Samba
  include: config-samba.yml

- name: Configure TGT
  include: config-tgt.yml

- name: Configure NFS
  include: config-nfs.yml
