---
# main nas pi tasks
- name: install pre-reqs
  include: install-pre-reqs.yml

- name: create directories
  file:
   path: "{{ item }}"
   state: directory
   owner: pi
   group: pi
  with_items:
   - '/mnt/pi_nas01/stream/tv'
   - '/mnt/pi_nas01/stream/movies'

#- name: create directories
#  file:
#   path: "{{ item }}"
#   state: directory
#   owner: pi
#   group: pi
#  with_items:
#   - '/mnt/external01'
#   - '/mnt/external02'

- name: add mounts to fstab
  lineinfile:
   path: /etc/fstab
   line: "{{ item }}"
   create: yes
  with_items:
   #- '10.10.125.52:/srv/data/stream/tv     /mnt/pi_nas01/stream/tv     nfs ro 0 0'
   #- '10.10.125.52:/srv/data/stream/movies /mnt/pi_nas01/stream/movies nfs ro 0 0'
   - '//pi-nas.local/stream-tv /mnt/pi_nas01/stream/tv cifs guest,uid=1000,iocharset=utf8 0 0'
   - '//pi-nas.local/stream-movies /mnt/pi_nas01/stream/movies cifs guest,uid=1000,iocharset=utf8 0 0'

- name: install plex
  include: plex.yml

