---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr_aduio
    environment:
      - PUID=2070
      - PGID=2070
      - TZ=America/New_York
    volumes:
      - /srv/docker/readarr/audio/config/:/config
      - /mnt/readarr/library:/data/library #optional
      - /mnt/readarr/downloads:/data/downloads #optional
    ports:
      - 8788:8787
    restart: unless-stopped
    dns:
      - 10.10.125.87
      - 1.1.1.1         

networks:
  default:
    external:
      name: arr_network
