---
password_salt: "{{ vault_password_salt }}"

samba_users: "{{ vault_samba_users }}"

vpn_credentials: "{{ vault_vpn_credentials }}"
vpn_config_path_src: "/home/ansible/openvpn/denmark.ovpn"
vpn_config_path_dest: "/etc/openvpn/pia.conf"

nzbget_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'nzb') | first }}"
bazarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'bazarr') | first }}"
sonarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'sonarr') | first }}"

conf_swapfactor: 2
conf_maxswap: 2048

sonarr_ended_settings:
  username: "sonarr"
  uid: "2000"
  groupname: "sonarr"
  gid: "2000"
  smb_creds: "{{ sonarr_smb_creds }}"
  smb_dir: "Videos/tv"
  data_dir_name: "tv"
  image_name: "linuxserver/sonarr"
  docker_dir: "srv/docker/sonarr/ended"
  service_name: "docker.sonarr.ended"
  systemd_script: "docker.sonarr.ended.service"
 
sonarr_tv_settings:
  username: "sonarr"
  uid: "2000"
  groupname: "sonarr"
  gid: "2000"
  smb_creds: "{{ sonarr_smb_creds }}"
  smb_dir: "Videos/tv"
  data_dir_name: "tv"
  image_name: "linuxserver/sonarr"
  docker_dir: "srv/docker/sonarr/tv"
  service_name: "docker.sonarr.tv"
  systemd_script: "docker.sonarr.tv.service"  
  
sonarr_anime_settings:
  username: "sonarr"
  uid: "2000"
  groupname: "sonarr"
  gid: "2000"
  smb_creds: "{{ sonarr_smb_creds }}"
  smb_dir: "Videos/tv"
  data_dir_name: "tv"
  image_name: "linuxserver/sonarr"
  docker_dir: "srv/docker/sonarr/anime"
  service_name: "docker.sonarr.anime"
  systemd_script: "docker.sonarr.anime.service"    
  
radarr_settings:
  username: "radarr"
  uid: "2050"
  groupname: "radarr"
  gid: "2050"
  smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'radarr') | first }}" 
  smb_dir: "Videos/movies"
  data_dir_name: "movies"
  image_name: "linuxserver/radarr"
  docker_dir: "srv/docker/radarr"
  service_name: "docker.radarr"
  systemd_script: "docker.radarr.service"   
  
lidarr_settings:
  username: "lidarr"
  uid: "2060"
  groupname: "lidarr"
  gid: "2060"
  smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'lidarr') | first }}" 
  smb_dir: "Music"
  data_dir_name: "music"
  image_name: "linuxserver/lidarr"
  docker_dir: "srv/docker/lidarr"
  service_name: "docker.lidarr"
  systemd_script: "docker.lidarr.service"   
  
readarr_settings:
  username: "readarr"
  uid: "2070"
  groupname: "readarr"
  gid: "2070"
  smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'readarr') | first }}" 
  smb_dir: "Library"
  data_dir_name: "library"
  image_name: "linuxserver/readarr:develop"
  docker_dir: "srv/docker/readarr"
  service_name: "docker.readarr"
  systemd_script: "docker.readarr.service"     

nzbget_credentials: "{{ vault_nzbget_user_credentials }}"
nzbget_username: "{{ nzbget_credentials.username }}"
nzbget_password: "{{ nzbget_credentials.password }}"
nzbget_uid: "2080"
nzbget_gid: "2080"

prowlarr_credentials: "{{ vault_prowlarr_user_credentials }}"
prowlarr_username: "{{ prowlarr_credentials.username }}"
prowlarr_password: "{{ prowlarr_credentials.password }}"

bazarr_credentials: "{{ vault_bazarr_user_credentials }}"
bazarr_username: "{{ bazarr_credentials.username }}"
bazarr_password: "{{ bazarr_credentials.password }}"
