---
samba_users: "{{ vault_samba_users }}"
vpn_credentials: "{{ vault_vpn_credentials }}"
nzb_creds: "{{ samba_users | selectattr('username', 'equalto', 'nzb') | first }}"
nzb_servers: "{{ vault_nzb_server }}"
sonarr_creds: "{{ samba_users | selectattr('username', 'equalto', 'sonarr') | first }}"
