---
password_salt: "{{ vault_password_salt }}"

samba_users: "{{ vault_samba_users }}"

dvr_credentials: "{{ vault_dvr_user_credentials }}"
dvr_username: "{{ dvr_credentials.username }}"
dvr_password: "{{ dvr_credentials.password }}"

vpn_credentials: "{{ vault_vpn_credentials }}"
vpn_config_path_src: "/home/ansible/openvpn/denmark.ovpn"
vpn_config_path_dest: "/etc/openvpn/pia.conf"

nzbget_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'nzb') | first }}"
sonarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'sonarr') | first }}"
bazarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'bazarr') | first }}"
radarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'radarr') | first }}"
lidarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'lidarr') | first }}"
readarr_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'readarr') | first }}"
lazyLibrarian_smb_creds: "{{ samba_users | selectattr('username', 'equalto', 'lazyLibrarian') | first }}"

nzbget_credentials: "{{ vault_nzbget_user_credentials }}"
nzbget_username: "{{ nzbget_credentials.username }}"
nzbget_password: "{{ nzbget_credentials.password }}"
nzbget_uid: "2080"
nzbget_gid: "2080"

prowlarr_credentials: "{{ vault_prowlarr_user_credentials }}"
prowlarr_username: "{{ prowlarr_credentials.username }}"
prowlarr_password: "{{ prowlarr_credentials.password }}"

bazarr_credentials: "{{ vault_bazarr_user_credentials }}"
bazarr_username: "{{ bazarr_credentials.username }}"
bazarr_password: "{{ bazarr_credentials.password }}"

radarr_credentials: "{{ vault_radarr_user_credentials }}"
radarr_username: "{{ radarr_credentials.username }}"
radarr_password: "{{ radarr_credentials.password }}"

sonarr_username: "sonarr"
sonarr_id: "2000"

lidarr_credentials: "{{ vault_lidarr_user_credentials }}"
lidarr_username: "{{ lidarr_credentials.username }}"
liadarr_password: "{{ lidarr_credentials.password }}"

readarr_credentials: "{{ vault_readarr_user_credentials }}"
readarr_username: "{{ readarr_credentials.username }}"
readarr_password: "{{ readarr_credentials.password }}"

lazyLibrarian_credentials: "{{ vault_lazyLibrarian_user_credentials }}"
lazyLibrarian_username: "{{ lazyLibrarian_credentials.username }}"
lazyLibrarian_password: "{{ lazyLibrarian_credentials.password }}"
