---
password_salt: "{{ vault_password_salt }}"

samba_users: "{{ vault_samba_users }}"

dvr_credentials: "{{ vault_dvr_user_credentials }}"
dvr_username: "{{ dvr_credentials.username }}"
dvr_password: "{{ dvr_credentials.password }}"

vpn_credentials: "{{ vault_vpn_credentials }}"
vpn_config_path_src: "/home/ansible/openvpn/denmark.ovpn"
vpn_config_path_dest: "/etc/openvpn/pia.conf"

nzb_creds: "{{ samba_users | selectattr('username', 'equalto', 'nzb') | first }}"
nzb_servers: "{{ vault_nzb_server }}"

sonarr_creds: "{{ samba_users | selectattr('username', 'equalto', 'sonarr') | first }}"
bazarr_creds: "{{ samba_users | selectattr('username', 'equalto', 'bazarr') | first }}"
radarr_creds: "{{ samba_users | selectattr('username', 'equalto', 'radarr') | first }}"
lidarr_creds: "{{ samba_users | selectattr('username', 'equalto', 'lidarr') | first }}"

prowlarr_credentials: "{{ vault_prowlarr_user_credentials }}"
prowlarr_username: "{{ prowlarr_credentials.username }}"
prowlarr_password: "{{ prowlarr_credentials.password }}"

bazarr_credentials: "{{ vault_bazarr_user_credentials }}"
bazarr_username: "{{ bazarr_credentials.username }}"
bazarr_password: "{{ bazarr_credentials.password }}"

radarr_credentials: "{{ vault_radarr_user_credentials }}"
radarr_username: "{{ radarr_credentials.username }}"
radarr_password: "{{ radarr_credentials.password }}"

lidarr_credentials: "{{ vault_lidarr_user_credentials }}"
lidarr_username: "{{ lidarr_credentials.username }}"
liadarr_password: "{{ lidarr_credentials.password }}"

