---
#requires ansible 2.9
#- name: set host name
#  hostname:  
#   name: "{{inventory_hostname}}"
#   use: debian

- name: Include vault
  include_vars:
    file: vault.yml

- name: set hostname
  lineinfile:
    path: /etc/hostname
    regexp: "^"
    line: "{{ inventory_hostname }}"
    state: present

- name: set hostname
  shell: sudo hostname {{inventory_hostname}}

- name: change default passwords
  user: name={{ item.username }} password={{ item.password }}
  with_items: "{{ system_users }}"
  loop_control:
    label: "{{ item.username }}"
