---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /srv/docker/homer/assets/:/www/assets
    ports:
      - 8088:8080
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=America/New_York
      - INIT_ASSETS=1 # default
    dns:
      - 10.10.125.87
      - 1.1.1.1

networks:
 default:
    external:
      name: arr_network

